#!/usr/bin/env python3

import subprocess

process_output = subprocess.run(["go", "test", "../..."], capture_output=True)

print(process_output.returncode)

#import webbrowser
#webbrowser.open('http://www.example.com')
