#!/usr/bin/python3

import subprocess

process_output = subprocess.run(["go", "test", "github.com/ornlu-is/go_git_hooks_example"], capture_output=True, text=True)

#import webbrowser
#webbrowser.open('http://www.example.com')
